  FROM mcr.microsoft.com/dotnet/aspnet:8.0
  COPY bin/Release/net8.0/publish/ app/
  WORKDIR /app
  EXPOSE 80
  ENV ASPNETCORE_URLS=http://+:80s
  ENTRYPOINT ["dotnet", "EShopOnAbp.AdministrationService.HttpApi.Host.dll"]