FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY eShopOnAbp ./eShopOnAbp
WORKDIR /src/eShopOnAbp/gateways/web-public/src/EShopOnAbp.WebPublicGateway
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0  AS final
WORKDIR /app
COPY --from=build /src/eShopOnAbp/gateways/web-public/src/EShopOnAbp.WebPublicGateway/bin/Release/publish/ .
ENTRYPOINT ["dotnet", "EShopOnAbp.WebPublicGateway.dll"]