apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - image: mcr.microsoft.com/mssql/server
          name: {{ .Release.Name }}-{{ .Chart.Name }}
{{- if eq .Release.Name "es-az" }}
          volumeMounts:
          - mountPath: "/var/opt/mssql"
            name: {{ .Release.Name }}-{{ .Chart.Name }}-database-volume
            subPath: sqlserver-data
{{- end }}
          ports:
            - name: sqlserver
              containerPort: 1433
          env:
          - name: SA_PASSWORD
            value: "myPassw@rd"
          - name: ACCEPT_EULA
            value: "Y"
{{- if eq .Release.Name "es-az" }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-{{ .Chart.Name }}-database-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-premium-retain"
      resources:
        requests:
          storage: 32Gi
{{- end }}